# Liste des bouteilles à surveiller sur Peak Wines (ou tout autre shop Shopify).
# name : nom affiché dans les notifications
# url  : URL de la fiche produit (sans paramètres ?_pos=... etc, pas nécessaire)

bottles:
  - name: "Lalù Langhe Nebbiolo 2024"
    url: "https://peak-wines.com/products/lalu_-langhe_nebbiolo_2024?_pos=1&_fid=1c4240494&_ss=c"

  - name: "Barbera d’Alba “Il Cerreto” 2021"
    url: "https://peak-wines.com/products/robertovoerzio-ilceretto-2021?_pos=6&_fid=411042c12&_ss=c"

  - name: "Ridolfi Rosso di Montalcino 2023"
    url: "https://peak-wines.com/products/ridolfi-rosso-2023?_pos=1&_fid=724039fed&_ss=c"

 - name: "Kellerei Terlan Terlaner 2025"
    url: "https://peak-wines.com/products/terlan-v-2025?_pos=1&_fid=13d9075e7&_ss=c"

  - name: "Catena Zapata Chardonnay Historic Rows 2022"
    url: "https://peak-wines.com/products/catenazapata-historicrows-chardonnay-2022?_pos=7&_fid=fd56e81bf&_ss=c"

  - name: "Dominio de Pingus PSI 2023"
    url: "https://peak-wines.com/products/psi-2023?_pos=3&_fid=f33c0c246&_ss=c"

